#!/bin/sh

cd scripts
go build -o baekjoon.exe ./cmd/baekjoon/main.go

cd ..
./scripts/baekjoon

status=$?

if [ $status -eq 0 ]; then
    git add scripts/cache.csv
    git add baekjoon/README.md
    exit 0
else
    exit 1
fi